### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by Charonxin** [PikachuHy/pscm#37]
### Search before asking

- [x] I searched the [issues](https://github.com/PikachuHy/pscm/issues) and found no similar issues.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

环境：

- ubuntu 22.04
- cmake 3.27.4
- clang version 16.0.6
- ninja version 1.10.1

日志：

```
CMake Error at 3rd/CMakeLists.txt:10 (target_sources):
  target_sources File set TYPE may only be "HEADERS"


CMake Error at 3rd/CMakeLists.txt:15 (target_sources):
  target_sources File set TYPE may only be "HEADERS"


CMake Error at 3rd/CMakeLists.txt:21 (target_sources):
  target_sources File set TYPE may only be "HEADERS"


CMake Error at 3rd/CMakeLists.txt:29 (target_sources):
  target_sources File set TYPE may only be "HEADERS"


CMake Error at 3rd/CMakeLists.txt:37 (target_sources):
  target_sources File set TYPE may only be "HEADERS"


CMake Error at CMakeLists.txt:89 (target_sources):
  target_sources File set TYPE may only be "HEADERS"


CMake Error at tool/pscm-build/src/CMakeLists.txt:8 (target_sources):
  target_sources File set TYPE may only be "HEADERS"
```

尝试：https://stackoverflow.com/questions/75444867/cmake-target-sources-file-set-type-may-only-be-headers

`option(PSCM_USE_CXX20_MODULES "enable c++20 modules" ON)`

无法生效。。。

**Comment by PikachuHy** [comment]
I will update to CMake 3.27  CMAKE_EXPERIMENTAL_CXX_MODULE_CMAKE_API value
different version of CMake has different value

**Comment by PikachuHy** [comment]
try the new version again

**Comment by Charonxin** [comment]
Finsh
